name: Docker CI

on:
  push:
    branches: ["main"]

jobs:
  build-dan-test:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode dari GitHub
        uses: actions/checkout@v3

      - name: Masak Image Docker
        run: docker build -t flask-app .

      - name: Tes Jalan
        run: docker run -d --name test-container -p 8080:5000 flask-app
