name: Build & Push ke Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Ambil kodenya
      - name: Checkout kode
        uses: actions/checkout@v4

      # 2. Siapkan Docker Buildx (Alat build canggih)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login ke Docker Hub (Pakai Secret yang baru kamu buat!)
      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Masak & Kirim! ðŸš€
      - name: Build dan Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Pastikan Dockerfile kamu ada di root folder
          push: true
          # Ini akan memberi nama image: username-kamu/flask-app:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest